erDiagram

Usuario{
    int id_usuario PK
    varchar nombre
    varchar apellido
    varchar dni
    varchar telefono
    varchar email
}
TipoUsuario{
    int id_tipoUsuario PK
    varchar nombre
    varchar descripcion
}
Casa{
    int id_casa PK
    varchar nombre
    varchar descripcion
}
StockCasa{
}
Producto{
    int id_producto PK
    varchar nombre
    varchar descripcion
}
Pedido{
    int id_pedido PK
    int id_casa FK
    int id_producto FK
}
Oferta{
}
Transporte{
    int id_transporte PK
    varchar marca
    varchar modelo
}

voluntarios 1--1+ voluntarios_casas: tiene