erDiagram

Usuario{
    int id_usuario PK
    varchar nombre
    varchar apellido
    varchar dni
    varchar telefono
    varchar email
}

TipoUsuario{
}
Casa{
}
Producto{
}
Pedido{
}
Oferta{
}
Transporte{
}

voluntarios 1--1+ voluntarios_casas: tiene