classDiagram
    class Direccion {
        - varchar calle
        - int numero
        - varchar localidad
        
        +setCalle()
        +setNumero()
        +setLocalidad()

        +getCalle()
        +getNumero()
        +getLocalidad()
    }