version: '3.8'

services:
  pe-db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'PRONTAENTREGADB'
      MYSQL_USER: 'itsv'
      MYSQL_PASSWORD: 'itsvpassword'
      MYSQL_ROOT_PASSWORD: 'itsvpassword'
      container_name: 'ProntaEntrega-mysql'
    ports:
         - "3307:3307"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      itsv:
        aliases:
          - mysql

  pe-phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_PASSWORD: 'itsvpassword'
      PMA_ARBITRARY: 1
      container_name: 'ProntaEntrega-phpmyadmin'
    ports:
      - "8080:80"
    networks:
      - itsv

  pe-django:
    image: django:5.0.3
    build: .
    container_name: 'pe-django'
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - pe-db
    networks:
      - itsv

networks:
  itsv:
    driver: bridge