version: '3.8'

services:
  pe-django:
    image: django:5.0.3
    command: >
      sh -c 'sleep 3 &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - pe-db
    networks:
      - itsv

  pe-db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'PRONTAENTREGADB'
      MYSQL_USER: 'itsv'
      MYSQL_PASSWORD: 'itsvpassword'
      MYSQL_ROOT_PASSWORD: 'itsvpassword'
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - itsv

  pe-phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_PASSWORD: 'itsvpassword'
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - itsv

networks:
  itsv:
    driver: bridge